package.path='./Scripts/?.lua;./Scripts/vendor/?.lua;'..package.path
local MC=require('mc')
local Objects=require('mc.objects')
local Widget=require('mc.widget')
assert(MC.valid==Objects.valid and MC.parent==Objects.parent)
assert(MC.load('objects')==Objects)
assert(MC('widget')==Widget and MC.load('widget')==Widget)
local ok,why=pcall(MC.load,'missing')
assert(not ok and tostring(why):find('unknown MC helper',1,true))
local directory=assert(os.getenv('MCT_TEST_DIR'),'MCT_TEST_DIR required')
local function write(name,content)
    local file=assert(io.open(directory..'/'..name,'wb'))
    assert(file:write(content))
    assert(file:close())
end
write('mc_sample.lua','return {name="sample"}\n')
write('entry.lua','local value=require("mc").template("sample"); return value\n')
assert(assert(loadfile(directory..'/entry.lua'))().name=='sample')
write('entry.lua','local value=require("mc").template("mc_sample.lua"); return value\n')
assert(assert(loadfile(directory..'/entry.lua'))().name=='sample')
write('custom.lua','return {name="custom"}\n')
write('entry.lua','local value=require("mc").template("custom.lua"); return value\n')
assert(assert(loadfile(directory..'/entry.lua'))().name=='custom')
write('mc_defaults.lua','return {name="own",settings={Size=75}}\n')
write('entry.lua',[[local MC=require('mc')
local defaults={module='VisualExample',name='shared',settings={Size=100}}
return MC.template('defaults',defaults),MC.template('defaults',defaults),defaults
]])
local first,second,defaults=assert(loadfile(directory..'/entry.lua'))()
assert(first.name=='own' and first.module=='VisualExample' and first.managed==nil)
assert(first.enabled==true and first.menuTarget=='module')
assert(first.settings.Size==75 and defaults.settings.Size==100)
first.menu[1]={id='changed'}
assert(#second.menu==0 and first.menu~=second.menu)
first.settings.Size=10
assert(second.settings.Size==75 and defaults.settings.Size==100)
ok,why=pcall(MC.template,'../sample')
assert(not ok and tostring(why):find('simple file stem',1,true))
ok,why=pcall(MC.template,'../sample.lua')
assert(not ok and tostring(why):find('simple Lua filename',1,true))
local entries,seen={},{}
MC._setTemplateRegistrar(function(path)
    if seen[path] then return false end
    seen[path]=true;entries[#entries+1]={path=path};return true
end)
write('provider.lua',[[local M=require('mc')
return M.registerTemplate('sample'),M.registerTemplate('sample')
]])
local added,duplicate=assert(loadfile(directory..'/provider.lua'))()
assert(added and duplicate==false)
assert(#entries==1 and entries[1].path==directory..'/mc_sample.lua')
ok,why=pcall(MC.registerTemplate,'sample',{})
assert(not ok and tostring(why):find('module manifest',1,true))
print('PASS: public MC object, widget, sibling template, and registration helpers')
